### ISSUE TITLE
Image upload in backend

### ISSUE THREAD

**Issue by realsahilsaini** [realsahilsaini/course-marketplace#2]
Add logic such that users, and admin can upload images (profiles, course thumbnails)

**Comment by nikkuv** [comment]
Hey @realsahilsaini assign it to me, I'll take it.

**Comment by realsahilsaini** [comment]
Go ahead...

**Comment by nikkuv** [comment]
@realsahilsaini can you provide the .env file varibales ? Not able to connect to the mongoDB.

**Comment by realsahilsaini** [comment]
You can create your own...It''s doesn't matter...
